pipeline {
    agent any

    environment {
        DOCKERHUB_USER = "manisha417"
        IMAGE_NAME = "java-maven:v1"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master', url: "https://github.com/DEV8428/simple-java-maven-app"
            }
        }

        stage('Build') {
            steps {
                echo "Building the project..."
                sh "mvn clean package"
            }
        }

        stage('Test') {
            steps {
                echo "Testing the code..."
            }
        }

        stage('Docker Build') {
            steps {
                echo "Building Docker image..."
                sh """
                    docker build -t manisha417/java-maven:v1 .
                    docker rm -f javaimage || true
                    docker run -d --name javaimage -p 8079:8080 manisha417/java-maven:v1
                """
            }
        }
    }
}
