pipeline {
    agent any

    stages {
        stage('Checkout'){
            steps {
                git "https://github.com/DEV8428/simple-java-maven-app"
            }
        }
        stage('build') {
            steps {
                echo 'Hello from build'
            }
        }
        stage('Test') {
           steps {
               echo "Testing the code..."
        }
    }
    stage ('Deploy'){   
        steps {
            echo "Deploymet in progress"
        }
        
    }
    }
}